/** Only references generated by the report-evidence media service are safe to expose. */
export function isSafeReportImageReference(value: unknown): value is string {
  if (typeof value !== 'string') return false;
  return /^\/(?:[a-z\d_-]+\/)*report-evidence\/\d{4}-\d{2}-\d{2}-[a-f\d]{8}-[a-f\d]{4}-[1-8][a-f\d]{3}-[89ab][a-f\d]{3}-[a-f\d]{12}\.(?:jpe?g|png)$/i.test(value);
}
