import { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useAuth } from '../../auth/hooks/useAuth';
import { acknowledgeResidentWarning, getResidentWarning } from '../api/residentWarningApi';
import type { ResidentWarning, WarningAcknowledgementResponse } from '@safealert/contracts';
import { dashboardTheme } from '../../dashboards/shared/theme';

export function ResidentWarningDetailsScreen() {
  const { warningId } = useLocalSearchParams<{ warningId: string }>(); const { accessToken } = useAuth(); const router = useRouter();
  const [warning, setWarning] = useState<ResidentWarning | null>(null); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false); const [response, setResponse] = useState<WarningAcknowledgementResponse | null>(null);
  useEffect(() => { if (!accessToken || !warningId) return; void getResidentWarning(warningId, accessToken).then(r => setWarning(r.warning)).catch(() => setError('This warning is unavailable.')); }, [accessToken, warningId]);
  const acknowledge = async () => { if (!accessToken || !warning || !response || saving) return; setSaving(true); try { const result = await acknowledgeResidentWarning(warning.id, { response }, accessToken); setWarning({ ...warning, acknowledgedAt: result.acknowledgedAt }); } catch { setError('Unable to acknowledge this warning.'); } finally { setSaving(false); } };
  if (!warning && !error) return <View style={styles.center}><ActivityIndicator color={dashboardTheme.colors.primary} /></View>;
  if (error || !warning) return <View style={styles.center}><Text style={styles.error}>{error ?? 'Warning unavailable.'}</Text><Pressable onPress={() => router.back()}><Text>Go back</Text></Pressable></View>;
  const attachments = warning.attachments ?? [];
  const options: Array<[WarningAcknowledgementResponse, string]> = [['SAFE', 'I am Safe'], ['EVACUATING', 'I am Evacuating'], ['NEED_ASSISTANCE', 'I Need Assistance']];
  return <ScrollView contentContainerStyle={styles.container}><Text style={[styles.risk, warning.riskLevel === 'CRITICAL' ? styles.critical : styles.high]}>{warning.riskLevel} WARNING</Text><Text style={styles.title}>{warning.affectedArea}</Text><Text style={styles.label}>Warning</Text><Text style={styles.body}>{warning.message}</Text><Text style={styles.label}>Required action</Text><Text style={styles.body}>{warning.requiredAction}</Text><Text style={styles.label}>Unsafe roads</Text><Text style={styles.body}>{warning.unsafeRoads}</Text>{warning.safeRoutes ? <><Text style={styles.label}>Safe routes</Text><Text style={styles.body}>{warning.safeRoutes}</Text></> : null}{attachments.length ? <><Text style={styles.label}>Attachments</Text>{attachments.map(a => <Text key={a} style={styles.body}>{a}</Text>)}</> : null}<Text style={styles.status}>{warning.acknowledgedAt ? `Acknowledged ${new Date(warning.acknowledgedAt).toLocaleString()}` : 'Not acknowledged'}</Text>{!warning.acknowledgedAt ? <View style={styles.responseCard}><Text style={styles.label}>How are you responding?</Text>{options.map(([value, label]) => <Pressable key={value} accessibilityRole="radio" accessibilityState={{ checked: response === value }} onPress={() => setResponse(value)} style={[styles.responseOption, response === value && styles.responseSelected]}><Text style={styles.responseText}>{label}</Text></Pressable>)}<Pressable disabled={saving || !response} onPress={() => void acknowledge()} style={[styles.button, !response && styles.buttonDisabled]}><Text style={styles.buttonText}>{saving ? 'Saving…' : 'Submit response'}</Text></Pressable></View> : null}<Pressable onPress={() => router.back()}><Text style={styles.back}>Back to active warnings</Text></Pressable></ScrollView>;
}
const styles = StyleSheet.create({ container: { padding: 20, gap: 12, backgroundColor: dashboardTheme.colors.background, flexGrow: 1 }, center: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 16 }, risk: { alignSelf: 'flex-start', color: '#fff', fontWeight: '900', padding: 8, borderRadius: 8 }, high: { backgroundColor: '#d97706' }, critical: { backgroundColor: dashboardTheme.colors.critical }, title: { fontSize: 24, fontWeight: '900', color: dashboardTheme.colors.text }, label: { fontWeight: '800', color: dashboardTheme.colors.muted, marginTop: 8 }, body: { color: dashboardTheme.colors.text, fontSize: 16, lineHeight: 23 }, status: { color: dashboardTheme.colors.primaryStrong, fontWeight: '800', marginTop: 12 }, responseCard: { gap: 9, padding: 14, marginTop: 8, borderRadius: 14, backgroundColor: dashboardTheme.colors.surface, borderWidth: 1, borderColor: dashboardTheme.colors.border }, responseOption: { minHeight: 44, justifyContent: 'center', paddingHorizontal: 12, borderRadius: 10, borderWidth: 1, borderColor: dashboardTheme.colors.border }, responseSelected: { borderColor: dashboardTheme.colors.primary, backgroundColor: dashboardTheme.colors.primarySoft }, responseText: { color: dashboardTheme.colors.text, fontWeight: '700' }, button: { minHeight: 50, alignItems: 'center', justifyContent: 'center', borderRadius: 12, backgroundColor: dashboardTheme.colors.primary, marginTop: 8 }, buttonDisabled: { opacity: 0.45 }, buttonText: { color: '#fff', fontWeight: '800' }, back: { color: dashboardTheme.colors.primaryStrong, fontWeight: '800', textAlign: 'center', marginTop: 10 }, error: { color: dashboardTheme.colors.critical } });
